apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ks-cli-pipelines
  namespace: ks-devops-ext
spec:
  project: default
  source:
    repoURL: https://github.com/kubesphere-sigs/ks
    targetRevision: HEAD
    path: .github/tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: ks-devops-ext
  syncPolicy:
    automated: {}
