apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../base
  - ../crds

images:
- name: quay.io/argoproj/argocd-applicationset
  newName: quay.io/argoproj/argocd-applicationset
  newTag: v0.2.0
