apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-zh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jenkins-zh/versions
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-zh
  syncPolicy:
    automated: {}