apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linuxsuren
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/linuxsuren/linuxsuren-versions
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: linuxsuren
  syncPolicy:
    automated: {}